### PR TITLE
Add version 1.7.1

### PR DESCRIPTION
**Pull request by phemmylintry**

### CODE REVIEW

**Review by parisk — CHANGES_REQUESTED** [review]
@phemmylintry let's rebase and run this against #44, as a chained PR. We should:

- [x] Merge #44 
- [x] Release `1.7.0`
- [x] Merge #45 (this)
- [x] Release `1.7.1`

**Comment by parisk** [comment]
@phemmylintry also please fix `ARG` syntax, which was broken #44 and slipped the review, but fixed in https://github.com/withlogicco/docker-poetry/pull/46.

**Review by gmargaritis — DISMISSED** [review]
LGTM 🍰

**Review by parisk — CHANGES_REQUESTED** [review]
Let's squash commits and we should be good to go.

**Review by parisk — APPROVED** [review]
LGTM 🦌

**Pull request merged**
